# Qiime2 version number
q2v: "2022.11"
# Qiime2 conda environment, copied from https://github.com/qiime2/environment-files
q2env: "envs/qiime2-2022.11-py38-linux-conda.yml"

# UNITE Major version listed in file names
version: "ver9"
# UNITE Publication version listed in the file names
date: "29.11.2022"

# UNITE Precluster percentage
cluster:
#  - "97" # If you need these, please let me know: https://github.com/colinbrislawn/unite-train/issues 
  - "99"
  - "dynamic"

# UNITE Taxa scope and singleton inclusion
type:
  - ""
  - "s_"
  - "all_"
  - "s_all_"
