# Qiime2 version number
q2v: "2023.5"
# Qiime2 conda environment
# Get full file from from https://github.com/qiime2/environment-files
# Or specify name of already installed Qiime2 environment
q2env: "qiime2-2023.5"
# Or load a pre-installed module
q2mod: "qiime2/2023.5"

# UNITE Major version listed in file names
version: "ver9"
# UNITE Publication version listed in the file names
date: "25.07.2023"

# UNITE Precluster percentage
cluster:
#  - "97" # If you need these, please let me know: https://github.com/colinbrislawn/unite-train/issues 
  - "99"
  - "dynamic"

# UNITE Taxa scope and singleton inclusion
type:
  - ""
  - "s_"
  - "all_"
  - "s_all_"
